theme: jekyll-theme-hacker
title: V-Research Educational
logo: https://repository-images.githubusercontent.com/293738808/29846400-2ff4-11eb-8a2e-d595a40f785e
show_downloads: true
google_analytics: UA-158261467-1
